name: CI

on:
  push:
    branches: [ master, main ]

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Super-Linter
      uses: super-linter/super-linter@v8.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run list script
      run: ./list.sh
    