name: CI

on:
  push:
    branches:
        - '**'

jobs:
  build:
    name: "Run build script"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run echoing script
        run: ./echo-script.bash
