name: CI

on:
  push:
    branches: [master, main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: TruffleHog OSS
        run: |
          docker run --rm -v "$PWD:/repo" trufflesecurity/trufflehog:latest filesystem /repo --no-update

      - name: Run list script
        run: bash ./list.sh
